name: Task
description: A new Flutter Task.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  get: ^4.6.5
  progress_loading_button: ^1.1.4
  flutter_secure_storage: ^5.0.2
  flutter_translate: ^3.0.1
  flutter_svg: ^1.1.1+1
  device_info_plus: ^9.0.2
  shamsi_date: ^1.0.1
  fluttertoast: ^8.1.2
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  contained_tab_bar_view_with_custom_page_navigator: ^0.1.3
  intl: any

flutter_icons:
  android: "luncher_icon"
  ios: true
  image_path: "assets/images/app/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

